# Generated by Django 5.2.5 on 2025-09-01 14:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="IR", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("weight", models.PositiveIntegerField()),
                ("craftingfee_buy", models.PositiveBigIntegerField()),
                ("craftingfee_sell", models.PositiveBigIntegerField()),
                ("Is_available", models.BooleanField()),
                ("bonakdaricode", models.CharField(max_length=30)),
                ("bonakdariname", models.CharField(max_length=40)),
            ],
        ),
    ]
